<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rrbot" params="parent prefix *origin">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value=".6" /> <!-- Link 3 -->
  <xacro:property name="height4" value=".25" /> <!-- Link 4 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <joint name="${prefix}base_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${prefix}base_link" />
  </joint>

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>

    </link>

    <joint name="${prefix}joint1" type="revolute">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="25" velocity="10" lower="-${pi}" upper="${pi}"/>
    </joint>

    <!-- Middle Link 1-->
    <link name="${prefix}link1">
     <collision>
        <origin xyz="${height2/2-width/2} 0 ${height1 + width/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${height2} ${width} ${width}"/>
        </geometry>
      </collision>
      

      <visual>
        <origin xyz="${height2/2-width/2} 0 ${height1 + width/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${height2} ${width} ${width}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      
      <inertial>
        <origin xyz="${height2/2-width/2} 0 ${height1 + width/2}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
          ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
          izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>

      <joint name="${prefix}joint2" type="revolute">
        <parent link="${prefix}link1"/>
        <child link="${prefix}link2"/>
        <origin xyz="${height2-axel_offset*2} 0 ${height1}" rpy="0 0 0"/>
        <limit effort="25" velocity="10" lower="-${pi}" upper="${pi}"/>
        <axis xyz="0 0 1"/>
      </joint>

      <!-- Middle Link 2-->
      <link name="${prefix}link2">
        <collision>
          <origin xyz="${height3/2 - width/2} 0 ${-width/2}" rpy="0 0 0"/>
          <geometry>
            <box size="${height3} ${width} ${width} "/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="${height3/2 - width/2} 0 ${-width/2}" rpy="0 0 0"/>
          <geometry>
            <box size="${height3} ${width} ${width} "/>
          </geometry>
          <material name="green"/>
        </visual>
        
        <inertial>
          <origin xyz="${height3/2 - width/2} 0 ${-width/2}" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
            ixx="${mass / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + height3*height3)}"/>
          </inertial>

      </link>

        <joint name="${prefix}joint3" type="prismatic">
          <origin xyz="${height3 - width} 0 0" rpy="0 0 0" />
          <parent link="${prefix}link2"/>
          <child link="${prefix}link3" />
          <limit effort="25" velocity="10" lower="-1" upper="0"/>
          <axis xyz="0 0 1"/>
        </joint>

      <!-- Top Link-->
      <link name="${prefix}link3">
        <collision>
          <origin xyz="$0 0 ${-height4/2+width}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height4}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 ${-(height4/2+width)}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height4}"/>
          </geometry>
          <material name="blue"/>
        </visual>

        <inertial>
          <origin xyz="0 0 ${-(height4/2+width)}" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
            ixx="${mass / 12.0 * (width*width + height4*height4)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height4*height4 + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + width*width)}"/>
          </inertial>
      </link>


        <joint name="${prefix}tool_joint" type="fixed">
          <origin xyz="0 0 ${-(height4+width)}" rpy="0 0 0" />
          <parent link="${prefix}link3"/>
          <child link="${prefix}tool_link" />
          <axis xyz="0 0 1"/>
        </joint>

      
        <!-- Tool Link -->
        <link name="${prefix}tool_link">
        </link>

  </xacro:macro>

</robot>
